### ISSUE TITLE
[CY-6514] Not using detekt.yml

### ISSUE THREAD

**Issue by Glennmen** [codacy/codacy-detekt#51]
I am using the [codacy github action](https://github.com/codacy/codacy-analysis-cli-action) on my Kotlin project but it doesn't seem to pickup my `detekt.yml` config in the root of my project.

I keep getting this error:
```
Found [Info] `Wildcard import` in src/main/kotlin/me/glennmen/bgmdiscordbot/extensions/RedeemCodeExtension.kt:10 (NoWildcardImports)
```

But in my detekt.yml I have:
```
  NoWildcardImports:
    active: true
    packagesToUseImportOnDemandProperty: 'java.util.*,kotlinx.android.synthetic.**'
    
  WildcardImport:
    active: true
    excludes: [ '**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**' ]
    excludeImports:
      - 'java.util.*'
```

The file in question has only this wildcard import:
```
import java.util.*
```

When running Detekt directly myself (using the config) everything is valid, so I am sure that my config is not being used by codacy.
